# Welcome to Jekyll!
#

# Site settings
title: Serverlessness
description: |
  Stop managing servers
  Spend time on content and functionality
  Spend time where it matters
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: jimmys.email@gmail.com
baseurl: "/spectral" # the subpath of your site, e.g. /blog
url: "http://www.github.io/jimmylin" # the base hostname & protocol for your site
social:
  github: https://github.com/jimmylin
  linkedin-square: https://linkedin.com/in/jimmy-lin-3639349
  facebook-official: https://facebook.com/lin.jimmy
  #email: jimmys.email@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
